insert into "public"."MANUFACTURER" ("names") values ('Oxford Industries, Inc.');
insert into "public"."MANUFACTURER" ("names") values ('CHS Inc');
insert into "public"."MANUFACTURER" ("names") values ('FIRST REPUBLIC BANK');
insert into "public"."MANUFACTURER" ("names") values ('X-Links Silver Shares Covered Call ETN');
insert into "public"."MANUFACTURER" ("names") values ('Nicholas Financial, Inc.');
insert into "public"."MANUFACTURER" ("names") values ('Aberdeen Singapore Fund, Inc.');
insert into "public"."MANUFACTURER" ("names") values ('Liberty Interactive Corporation');
insert into "public"."MANUFACTURER" ("names") values ('Nivalis Therapeutics, Inc.');
insert into "public"."MANUFACTURER" ("names") values ('TransAct Technologies Incorporated');
insert into "public"."MANUFACTURER" ("names") values ('SAExploration Holdings, Inc.');

insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Cloves - Whole', 321.7, '5/2/2021', 1);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Apple - Northern Spy', 3483.35, '6/7/2021', 5);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Bacardi Breezer - Strawberry', 383.81, '7/3/2021', 3);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Arizona - Plum Green Tea', 2334.05, '2/8/2021', 6);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Bar Special K', 671.45, '6/2/2021', 4);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Appetizer - Smoked Salmon / Dill', 3191.63, '5/8/2021', 1);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Magnotta - Bel Paese White', 698.89, '6/1/2021', 6);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Shrimp - 16/20, Iqf, Shell On', 778.2, '3/2/2021', 5);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Hold Up Tool Storage Rack', 3637.77, '1/8/2021', 3);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Wine - Cotes Du Rhone Parallele', 1469.61, '4/2/2021', 7);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Cheese - Shred Cheddar / Mozza', 1155.33, '4/6/2021', 2);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Oranges - Navel, 72', 2979.93, '3/2/2021', 4);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Wine - Gato Negro Cabernet', 1220.27, '3/3/2021', 7);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Cheese - Feta', 1913.18, '5/6/2021', 9);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Oil - Olive', 3363.87, '5/10/2021', 2);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Chicken Giblets', 4848.1, '9/8/2021', 9);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Honey - Lavender', 484.47, '11/5/2021', 8);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Tea - Mint', 1492.7, '4/2/2021', 1);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Beef - Bones, Cut - Up', 3401.66, '2/3/2021', 3);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Wine - Chateau Timberlay', 3052.49, '11/2/2021', 4);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Longos - Burritos', 2740.6, '5/1/2021', 6);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Wine - Red, Harrow Estates, Cab', 4104.96, '12/2/2020', 7);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Food Colouring - Orange', 558.04, '3/9/2021', 3);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('The Pop Shoppe - Grape', 2160.05, '3/2/2021', 1);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Chocolate - Mi - Amere Semi', 3865.96, '4/5/2021', 8);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Pork Ham Prager', 1033.33, '7/8/2021', 1);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Rum - Mount Gay Eclipes', 2733.37, '5/2/2021', 2);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Parasol Pick Stir Stick', 2789.57, '2/5/2021', 8);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Appetizer - Cheese Bites', 2794.64, '2/1/2021', 4);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Mikes Hard Lemonade', 3307.95, '7/5/2021', 10);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Cake - Cake Sheet Macaroon', 4044.0, '12/7/2020', 6);
insert into "public"."PRODUCT" (title, cost, MANUFACTURE_DATE, MANUFACTURER_ID) values ('Wine - Riesling Alsace Ac 2001', 3137.46, '8/3/2021', 7);

select * from "public"."MANUFACTURER";